### ISSUE TITLE
public interface mintWithPermission must not have uint256 tokenId as it introduces synchronicity requirement for callers

### ISSUE THREAD

**Issue by TimDaub** [rugpullindex/ERC4973#19]
- consider two people trying to mint their ABR at the same time
- One of them will fail unnecessarily because the tokenId is taken by the transactor in front
- Rather, dynamically, the contract should lead the increase of token id through e.g. incrementing and keeping track

**Comment by rahulrumalla** [comment]
Using Counters and then return the new tokenId, yeah?

**Comment by rahulrumalla** [comment]
Although I wouldn't call this a bug but an enhancement :)

**Comment by TimDaub** [comment]
> Using Counters and then return the new tokenId, yeah?

yes

**Comment by TimDaub** [comment]
> Although I wouldn't call this a bug but an enhancement :)

It's a bug because something isn't working. It's a must have not a should have.

**Comment by rahulrumalla** [comment]
I take this up as well as I need this change rather quickly and I'm in the middle of all of this. Please assign it to me if you agree and I can issue a PR soon
