### ISSUE TITLE
mintWithPermission is infinitely callable but should only be callable once per type hash voucher

### ISSUE THREAD

**Issue by TimDaub** [rugpullindex/ERC4973#22]
- Say we have `from` giving their permission to mint `tokenURI` to `to`, then we'd expect that by `signing` the type hash once, they'd permit minting "once" and not "many times".
- However, in `mintWithPermission` any `to` can mint an near infinite amount of equal tokens with an incrementing tokenId.
- We should consider invalidating already used permission vouchers by e.g. checking if they've been used.

Interestingly, a bloom filter could serve as a gas-optimized lookup table with the drawback of potentially being false positive but never false negative: 

> A Bloom filter is a space-efficient [probabilistic](https://en.wikipedia.org/wiki/Probabilistic) [data structure](https://en.wikipedia.org/wiki/Data_structure), conceived by [Burton Howard Bloom](https://en.wikipedia.org/w/index.php?title=Burton_Howard_Bloom&action=edit&redlink=1) in 1970, that is used to test whether an [element](https://en.wikipedia.org/wiki/Element_(mathematics)) is a member of a [set](https://en.wikipedia.org/wiki/Set_(computer_science)). [False positive](https://en.wikipedia.org/wiki/Type_I_and_type_II_errors) matches are possible, but [false negatives](https://en.wikipedia.org/wiki/Type_I_and_type_II_errors) are not – in other words, a query returns either "possibly in set" or "definitely not in set".

- https://en.wikipedia.org/w/index.php?title=Bloom_filter&oldid=1093645614

More details on membership proof data structures: https://github.com/rugpullindex/awesome-ethereum-rollups#membership-proof-data-structures

Alternatively, we can just store a "usedVouchers" mapping.

**Comment by TimDaub** [comment]
Alternatively, since all vouchers could be represented by a uint256, potentially setting a flag in a uin256 bitmap may work well too. Potentially this function could be repurposed: https://github.com/rugpullindex/indexed-sparse-merkle-tree/blob/36ae144f78fb8ffc9111fd45bd7f024b01ad7aa7/src/StateTree.sol#L10

**Comment by TimDaub** [comment]
implementation: https://docs.openzeppelin.com/contracts/4.x/api/utils#BitMaps

**Comment by rahulrumalla** [comment]
Ah good catch! This is mainly happening because of our move to Counters. 

This is essentially what I intended to do with chain-claim earlier 
https://github.com/otterspace-xyz/chain-claim/blob/vouchers/src/ChainClaim.sol

**Comment by TimDaub** [comment]
> implementation: https://docs.openzeppelin.com/contracts/4.x/api/utils#BitMaps

We can use OZ's bitmaps here. Essentially, we can use the type hash's `bytes32` as the bitmaps flag's index

```sol
bytes32 hash = getMintPermitMessageHash(...);
uint256 index = uint256(hash);
set(bitmap, index);
```

**Comment by rahulrumalla** [comment]
Yeah! Nice. 

Becuase `tokenURI` is part of typehash, the key in the bitmap would be unique i.e., a `from` address can issue multiple "permissioned vouchers" to the `to` address to mint.

**Comment by TimDaub** [comment]
> Yeah! Nice.
> 
> Becuase `tokenURI` is part of typehash, the key in the bitmap would be unique i.e., a `from` address can issue multiple "permissioned vouchers" to the `to` address to mint.

yeah, this makes me somehow excited. I like the dynamic this creates!

**Comment by rahulrumalla** [comment]
Will you work on this or shall I pick this one up as well?

**Comment by rahulrumalla** [comment]
Considering that bitmap has a mapping of uint256 to uint256, I'm curious how we can take work with a typehash as a key since it is bytes32 🤔

**Comment by rahulrumalla** [comment]
Deleted my earlier comments 😅 I think I figured out the casting. Picking this up.
