### ISSUE TITLE
Risk in _mint() not using Counters

### ISSUE THREAD

**Issue by rahulrumalla** [rugpullindex/ERC4973#27]
https://github.com/rugpullindex/ERC4973/blob/5e7d50ec62d9592f425c4cccd2fc3c3b8aca48c1/src/ERC4973.sol#L70

I'm curious about the decision to not use counters for `_mint(...)`. 

If an ABT inherits `ERC4973Permit` can access both `_mint` and `mintWithPermission`, the calls to `_mint` would throw the tokenId counter out of sync if the implementor uses a local. Or rather, there isn't a way to fetch the current tokenId for the ABT to increment the counter on its own. 

See example below if an ABT inherits `ERC4973Permit` but intends to use `_mint`.

```solidity
contract ABT is ERC4973Permit {
  using Counters for Counters.Counter;
  Counters.Counter private _tokenIds;

  function mint(
    address to
  ) external returns (uint256) {
    uint256 newTokenId = _tokenIds.current();
    _mint(to, newTokenId, uri);
    _tokenIds.increment();
    return newTokenId;
  }
}
```

I think we have to make `_mint(...)` work with counters and not take in a tokenId as a parameter. Wdyt?

**Comment by TimDaub** [comment]
`_mint` is internal so only the developer could access it and then they can proxy it with a function as you mentioned. So IMO it is not a concern as I assume developers know what they're doing here.

**Comment by rahulrumalla** [comment]
But there isn't a way to reliably get the current `tokenId`, right? Or from a design perspective, do you not intend to support that?
