### ISSUE TITLE
Question: How to call mintFromPermission from front-end?

### ISSUE THREAD

**Issue by rahulrumalla** [rugpullindex/ERC4973#28]
Since mintWithPermission now takes the `bytes signature` param instead of v,r,s params, what's the best way to construct this using ethers.js ?

**Comment by TimDaub** [comment]
https://eips.ethereum.org/EIPS/eip-2098#reference-implementation

**Comment by TimDaub** [comment]
https://docs.ethers.io/v5/single-page/#/v5/api/utils/bytes/-%23-Signature
