### ISSUE TITLE
Decleration shadow for tokenURI

### ISSUE THREAD

**Issue by markcutajar** [rugpullindex/ERC4973#38]
I used yarn link, to link this into a brand new project with the idea of trying this out before using. 

Got a shadow decleration at compile time. (See logs below). It might be a good idea to use `uri` instead of `tokenURI` in the `_getHash` function. Can push the PR if you agree.

```
Warning: This declaration shadows an existing declaration.
   --> eip4973/src/ERC4973.sol:123:5:
    |
123 |     string calldata tokenURI
    |     ^^^^^^^^^^^^^^^^^^^^^^^^
Note: The shadowed declaration is here:
  --> eip4973/src/ERC4973.sol:56:3:
   |
56 |   function tokenURI(uint256 tokenId) public view virtual override returns (string memory) {
   |   ^ (Relevant source part starts here and spans across multiple lines).
```

**Comment by TimDaub** [comment]
OK so I guess we'd be better off renaming https://github.com/rugpullindex/ERC4973/blob/d9befc6bd27a6c6740206302b1d5f463253fc7c0/src/ERC4973.sol#L123 to something other, e.g. "URI"
