### ISSUE TITLE
Question: why is from address in TransferEvent hardcoded to address(0)?

### ISSUE THREAD

**Issue by rahulrumalla** [rugpullindex/ERC4973#39]
Hello. I'm confused about why the from address in TransferEvent supressed and hardcoded to address(0)?
https://github.com/rugpullindex/ERC4973/blob/25bb347db0448842964d375e887b295663ee97ed/src/ERC4973.sol#L149

**Comment by TimDaub** [comment]
it's wrong. for take it should be `from` and for give it should be `msg.sender`

**Comment by rahulrumalla** [comment]
One way to do it could be that we add the `from` field to the `_mint()`, but it would break a bunch of tests & will need updating. I wonder if we can make `_mint()` private as both `give` and `take` are marked external anyway. 

On a related matter, could we do with mint & burn being private in favour of give/take/unequip already being external?

**Comment by TimDaub** [comment]
I don't see the benefit of declaring _mint and _burn as private. What would be the argument for doing that?

I'm pro adding address _from to _mint that then gets used when emitting the Transfer event.

**Comment by rahulrumalla** [comment]
Oh, scratch that, I didn't think it through completely. We need mint/burn to be internal & virtual so implementors have the flexibility to override the core functionality and their own needs around it. 

Going back to adding the `from` field to `_mint()`, I think it would break a bunch of tests. If we add a `from` here to the `mint()`, shall we just add an arbitrary "from" address? Wdyt?

```solidity
  function testMint() public {
    string memory tokenURI = "https://example.com/metadata.json";
    uint256 tokenId = 0;
    abt.mint(msg.sender, tokenId, tokenURI);
    assertEq(abt.tokenURI(tokenId), tokenURI);
    assertEq(abt.ownerOf(tokenId), msg.sender);
  }
```

Btw, I can take this issue on and send a PR

**Comment by TimDaub** [comment]
> f we add a `from` here to the `mint()`, shall we just add an arbitrary "from" address? Wdyt?

If the test's purpose is to test _mint then yes, an arbitrary `from` can be defined within the test case.

**Comment by TimDaub** [comment]
> Btw, I can take this issue on and send a PR

I'd appreciate it
