### ISSUE TITLE
Inclusion of uri in Transfer event

### ISSUE THREAD

**Issue by rahulrumalla** [rugpullindex/ERC4973#40]
Speaking mostly from otterspace side as an implementor. Could benefit a ton by having uri as part of the transfer event, even if its not indexed. Were there any particular reasons that informed it's exclusion? 

Currently we're implement a custom event in the calling contract.

**Comment by TimDaub** [comment]
> Speaking mostly from otterspace side as an implementor. Could benefit a ton by having uri as part of the transfer event

Why?

**Comment by rahulrumalla** [comment]
Could then parse logs and fetch all the state data that informed that mint in that single context. Otherwise, we'd have to make another call to fetch the tokenUri via the tokenId. It's mostly for efficiency and convenience.

**Comment by TimDaub** [comment]
Several problems come to mind thinking about this proposal:

- event signature identifiers are formed using keccak-256, so adjusting the event signature ultimately means that people indexing for topic0 keccak(Transfer(from, to, tokenId)) wouldn't get expected results anymore.
- I'm not sure about the gas costs of emitting the fourth parameter

Generally, you're free to emit an additional even within the standard of EIP-4973, I think. Convenience as to not make an additional call to the chain, I'm not sure is a convincing argument to break backward compatibility with e.g. the EIP-721 event signature.

**Comment by rahulrumalla** [comment]
> I'm not sure is a convincing argument to break backward compatibility with e.g. the EIP-721 event signature.

Ah!! Interesting! Preserving backward compatibility is def a priority and this makes sense. Closing this. Thanks.
