### ISSUE TITLE
Cannot import ERC4793.sol from NPM package

### ISSUE THREAD

**Issue by markcutajar** [rugpullindex/ERC4973#43]
When running an import of ERC4973.sol i am getting this error:

```Error HH404: File ./ERC165.sol, imported from erc4973/src/ERC4973.sol, not found.```

Code used: 
```
# Yarn add erc4973
# then:
import "erc4973/src/ERC4973.sol";
```

Seems like it has a relative import but the file ERC165 is missing from the package even though in the original repo when it was being tested.

**Comment by TimDaub** [comment]
makes sense, we have to add all files that e.g. are imported here: https://github.com/rugpullindex/ERC4973/blob/bb471bcdc6a5871731566debeab97766e4423bbb/package.json#L5

**Comment by TimDaub** [comment]
pls try installing v0.4.0 from npm and let me know if it fixes it, thx
